services:

  # 1. Database Service
  db:
    image: postgres:16
    container_name: nodify-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: transitops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nodify-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. FastAPI Backend Service
  web:
    build: .
    container_name: transitops-backend-app
    ports:
      - "8000:8000"
    # REMOVE OR COMMENT OUT THIS LINE:
    # volumes:
    #   - .:/app 
    
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/transitops_db
      - RESEND_API_KEY=${RESEND_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nodify-network
    
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - __pycache__/
            - .venv/
            - .git/
        - action: rebuild
          path: ./requirements.txt

volumes:
  postgres_data:

networks:
  nodify-network: